# jazzy -m TwitterAPI -x -project,TwitterAPI.xcodeproj,-scheme,TwitterAPI-Package

module: TwitterAPI
author: Kevin Machado
author_url: https://github.com/djnivek
github_url: https://github.com/djnivek/TwitterAPI

output: Docs/swift

exclude:
  - "**/*-ObjC.swift"
  - "**/*Deprecations.swift"

clean: true
skip_undocumented: true

theme: apple

# custom_categories:
#     - name: TwitterAPI
#       children:
#       - TwitterAPI
#
#     - name: Models
#       children:
#       - User
#       - Media
#       - Comment
#
#     - name: Routes
#       children:
#       - Instagram
#       - Routes
#
#     - name: Network
#       children:
#       - Provider
