version: 2
jobs:
  branches:
      only:
        - develop
  test:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: fastlane scan

workflows:
  version: 2
  test_release:
    jobs:
      - test
