version: 2
jobs:
  test:
    macos:
      xcode: "10.1.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run: swift build
      - run: fastlane testAPI

workflows:
  version: 2
  test_release:
    jobs:
      - test
