# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_each do
#ensure_git_status_clean
end

platform :ios do

  desc "Bump the version to the given one"
  lane :bumpVersion do |options|
    version = options[:version_number]
    increment_version_number(
      version_number: version,
      xcodeproj: "TwitterAPI.xcodeproj"
    )
    git_commit(
      path: ".",
      message: "Version bump to #{version}"
    )
  end

    desc "Test the TwitterAPI"
    lane :testAPI do
      scan(
        devices: ["iPhone 6s", "iPhone X"]
      )
    end

end
